import gql from 'graphql-tag'

export const QUERY_ALL_STUDENTS = gql `
    query allStudents {
        allStudents{
            id
            name
            email
        }
}`;
export const QUERY_SINGLE_STUDENT = gql`
query singleStudent($studentId: ID!) {
  Student(id: $studentId) {
    id,
    email,
    name,
    softDelete
  }
  }`;


export const CREATE_STUDENT_MUTATION = gql `
    mutation CreatStudent($email: String!, $name: String!, $softDelete: Boolean!) {
        createStudent(name: $name, email: $email, softDelete: $softDelete) {
            id
            name
            email
        }
    }
`;
