import gql from 'graphql-tag'

export const QUERY_SINGLE_STUDENT = gql `
query singleStudent($studentId: ID!) {
  Student(id: $studentId) {
    id,
    email,
    name,
    softDelete
  }
  }`;

  export const QUERY_ALL_STUDENTS = gql `
  query allStudents {
    allStudents{
      id
      name
      email
    }
    }`;

    export const UPDATE_SINGLE_STUDENT = gql `
    mutation updateStudent($studentId: ID!, $name: String!, $email: String!) {
      updateStudent(id: $studentId, name: $name, email: $email) {
        id
        name
        email
      }
      }`;

      export const CREATE_STUDENT_MUTATION = gql `
      mutation createStudent($email: String!, $name: String!, $softDelete: Boolean!) {
        createStudent(name: $name, email: $email, softDelete: $softDelete) {
          id
          name
          email
        }
      }`;
