import gql from 'graphql-tag'

export const QUERY_SINGLE_STUDENT = gql `
query singleStudent($studentId: ID!) {
  Student(id: $studentId) {
    id,
    email,
    name,
    softDelete,
    group{
      id
      name
    },
    studentEvents {
      id,
      courseName,
      start
    }
  }
  }`;

  export const QUERY_MEMBER_STUDENT = gql`
  query memberStudent($thestudentId: ID!, $theauthorId: ID!) {
    Student(id: $thestudentId){
      id
      name
      group{
        id
        name
      }
      implementations {
        id
        weight
        urlRepo
        urlProject
        project {
          id
          name
        }
        scores(
          filter:{
            meeting:{
              author:{
                id: $theauthorId
              }
            }
          }
          ){
            id
            score
            comment
          }
        }
      }
      }`;

  export const QUERY_ALL_STUDENTS = gql `
  query allStudents {
    allStudents{
      id
      name
      email
      group {
        id
        name
      }
    }
    }`;

    export const UPDATE_SINGLE_STUDENT = gql `
    mutation updateStudent($studentId: ID!, $name: String!, $email: String!, $group: String!) {
      updateStudent(id: $studentId, name: $name, email: $email, group: $group) {
        id
        name
        email
        group
      }
      }`;

    export const CREATE_STUDENT_MUTATION = gql `
    mutation createStudent($email: String!, $name: String!, $softDelete: Boolean!, $groupId: ID!) {
      createStudent(name: $name, email: $email, softDelete: $softDelete, groupId: $groupId) {
        id
        name
        email
        group{
          id
        }
      }
      }`;
