import gql from 'graphql-tag'

export const QUERY_SINGLE_EVENT = gql`
query singleEvent($eventId: ID!){
  Event(id: $eventId) {
    id
    academicYear
    courseName
    jurys{
      id
      name
      softDelete
      email
      password
    }
    projects{
      id
      name
      weight
      description
    }
    softDelete
    start
    students{
      id
      name
      email
      group{
        id
        name
      }
    }
  }
  }`;

export const QUERY_ALL_EVENTS = gql`
query AllEvents($authorId: ID!){
  allEvents (orderBy: start_DESC, filter: { author: {id: $authorId}}){
    id
    academicYear
    author {
      id
      name
    }
    courseName
    implementations {
      id
      project {
        id
        name
      }
    }
    jurys {
      id
      name
    }
    meetings {
      id
      student {
        id
        name
        group {
          id
          name
        }
      }
    }
    performances {
      id
      student {
        id
        name
      }
    }
    projects {
      id
      name
      weight
    }
    softDelete
    start
    students {
      id
      name
    }
  }
}`;

export const QUERY_FEW_EVENTS = gql`
query allEvents($authorId: ID!){
  allEvents (orderBy: start_ASC, last:3,
    filter: {
      author: {
        id: $authorId
        }
    }){
    id
    courseName
    start
    author{
      id
      name
    }
    students{
      id
      name
    }
    projects{
      id
      name
    }
    jurys{
      id
      name
    }
  }
}`;

export const CREATE_EVENT_MUTATION = gql`
mutation createEvent($academicYear: String!, $courseName: String!, $softDelete: Boolean!, $eventStart: DateTime! $authorId: ID!, $jurysIds: [ID!], $studentsIds: [ID!], $projectsIds: [ID!]){
   createEvent(
     academicYear: $academicYear
     courseName: $courseName
     softDelete: $softDelete
     start: $eventStart
     authorId: $authorId
     jurysIds: $jurysIds
     studentsIds: $studentsIds
     projectsIds: $projectsIds
   ) {
   id
   students{
     id
     name
   }
   projects{
     id
     name
   }
   }
}`;
